### ISSUE TITLE
refresh_token 未必是以OAQ开头，但只要运行成功应该就ok了

### ISSUE THREAD

**Issue by AnRookies** [wangziyingwen/AutoApiSecret#1]
我的refresh_token就是以0.AS开头

再留个成功续期的截图：
![image](https://user-images.githubusercontent.com/57837252/76407960-29412b80-63c7-11ea-972e-ce435853f3fe.png)
嘿嘿~

**Comment by wangziyingwen** [comment]
OK，我其实就想让他们看看格式，因为有一小部分人会复制错。
我这就改改，谢谢提供
