### ISSUE TITLE
我的testapi信息有点怪

### ISSUE THREAD

**Issue by tsukiikekaoru** [wangziyingwen/AutoApiSecret#10]
Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  python 2.py
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.2/x64
4调用成功1次
5调用成功2次
6调用成功3次
7调用成功4次
9调用成功5次
10调用成功6次
此次运行结束时间为 : Thu May  7 10:17:09 2020
4调用成功7次
5调用成功8次
6调用成功9次
7调用成功10次
9调用成功11次
10调用成功12次
此次运行结束时间为 : Thu May  7 10:17:15 2020
4调用成功13次
5调用成功14次
6调用成功15次
7调用成功16次
9调用成功17次
10调用成功18次
此次运行结束时间为 : Thu May  7 10:17:22 2020

直接从4开始，然后循环了3遍

**Comment by wangziyingwen** [comment]
等onedrive激活成功
