### ISSUE TITLE
API 6和7重复了

### ISSUE THREAD

**Issue by yang05051** [wangziyingwen/AutoApiSecret#11]
两个都是：
graph.microsoft.com/v1.0/me/mailFolders/inbox/messageRules

建议把其中一个改成：
graph.microsoft.com/v1.0/me/mailFolders/inbox
即删掉messageRules后缀，同样可以调用成功

**Comment by wangziyingwen** [comment]
这个重复很早就发现了。由于secret的脚本整个都是原教程的脚本，为了保证一致性，而且重复并无大碍，可能不打算更改。（super版已经去重了）
等我有空看看原教程，脚本有没有更新再作打算。

**Comment by yang05051** [comment]
好的
