### ISSUE TITLE
我分配了powerbi的访问权限，为什么还是无法调用？

### ISSUE THREAD

**Issue by yang05051** [wangziyingwen/AutoApiSecret#12]
我按照官方文档分配了 powerbi 工作区 的读取权限
![387](https://user-images.githubusercontent.com/31024419/81463075-3d4bb280-91e9-11ea-98f4-e8c508882132.png)

但在尝试调用api.powerbi.com/v1.0/myorg/groups的时候，返回代码一直是403或者500（访问被拒绝了吧）
![385](https://user-images.githubusercontent.com/31024419/81463093-6f5d1480-91e9-11ea-85c4-ca87ed0bb297.png)
![386](https://user-images.githubusercontent.com/31024419/81463095-708e4180-91e9-11ea-830e-5b0b4819878b.png)

请问有解决方案嘛？

**Comment by yang05051** [comment]
我用官方的调用这个API是成功的
![388](https://user-images.githubusercontent.com/31024419/81463378-ccf26080-91eb-11ea-8f9a-04c29c281296.png)

**Comment by wangziyingwen** [comment]
powerbi的登录授权方式跟graph的不一样，好像不是v2，是beta还是啥的。header也不一样好像。具体你去看看powerbi的官方文档吧。
同样无碍，不打算处理。
