### ISSUE TITLE
正常运行一天后出了错误

### ISSUE THREAD

**Issue by imldy** [wangziyingwen/AutoApiSecret#16]
您好，我的正常运行了1天多之后在Test Api那边提示
```
Traceback (most recent call last):
  File "2.py", line 86, in <module>
    main()
  File "2.py", line 42, in main
    access_token=gettoken(refresh_token)
  File "2.py", line 31, in gettoken
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
```
然后我重新手动更改了1.tx中的trefresh_token和secret-CONFIG_KEY中的机密之后，运行之后Test Api那边提示：
```
  File "2.py", line 13
    ***
     ^
SyntaxError: invalid syntax
```
麻烦您看下怎么回事。

**Comment by imldy** [comment]
刚想起一点，就是我的子账号也注册了一个应用并且在别的平台开启了调用API。不知道跟这个有没有关系。我去确认一下

**Comment by imldy** [comment]
第二个报错是因为我更新CONFIG_KEY时忘记加上`secret=r''`了，我又注册了一个应用放在了fork自您的项目里面，目前可以正常运行，原来注册的程序用原博主的脚本在我云服务器上调用。但是目前还是没有找到第一次报错的原因，我再查证一下。

**Comment by wangziyingwen** [comment]
第一个需要重新获取token替换1.txt。

原因不明，出现几率太小，目前反馈只有不到10个的类似情况。猜测触发微软某种安全策略，导致token过期失效。

**Comment by imldy** [comment]
> 第一个需要重新获取令牌替换1.txt。
> 
> 原因不明，出现几率太小，目前反馈只有不到10个的类似情况。引发触发微软某种安全策略，导致令牌过期失效。

好的，谢谢回复，那我就不再找原因了😁
