### ISSUE TITLE
push失败

### ISSUE THREAD

**Issue by lengyihan7** [wangziyingwen/AutoApiSecret#2]
你原来的设置是可以成功的，我把1.py的那个rang改成了1500，然后运行到push的时候就会失败。报错128。如图：
![Snipaste_2020-03-18_20-09-55](https://user-images.githubusercontent.com/28485028/76960325-2bbafc80-6956-11ea-8ff6-a7e8139e65ad.png)
![Snipaste_2020-03-18_20-10-32](https://user-images.githubusercontent.com/28485028/76960334-2f4e8380-6956-11ea-82c5-2843e8a40e6f.png)
![Snipaste_2020-03-18_20-10-51](https://user-images.githubusercontent.com/28485028/76960339-307fb080-6956-11ea-8ba8-07cfc1e43f1f.png)
好像是用户名密码失效了，你知道这个怎么改吗？好像也不影响代码的执行哈。就是一直报错。

**Comment by kinoscfonemanger** [comment]
不知道，按理不会失效啊。你把personal access token删了再建一个试试？1500轮，3小时运行时间不好试验 ORZ。
这个push change是把新的refresh token更新进仓库。失败的话，后面的任务会一直用旧的refresh token。问题是refresh token有有效期，最后会导致登不进微软，api调用失败。

解决办法：
1，你要是会代码的话，可以分工，把更新token的代码提出来，新建一个workflow专门用来更新token。旧workflow专门用来运行api调用。你要是要的话，我可以帮你写一个酱紫。
2，启动次数增多，每次轮数减少。每10分钟3轮这样子。应该就不会出错了吧？

我觉得把，并不用这么频繁，一天一次都嫌多。开发应用不一定每时每刻都在调用api，大部分时间是在写代码。所以吧，我觉得“开发活跃”是只要偶尔调用一下就行了。毕竟以前的人都是搭个oneindex就续成了，在最后一个月调用一下outlook也续成了。

**Comment by wangziyingwen** [comment]
不知道，按理不会失效啊。你把personal access token删了再建一个试试？1500轮，3小时运行时间不好试验 ORZ。
这个push change是把新的refresh token更新进仓库。失败的话，后面的任务会一直用旧的refresh token。问题是refresh token有有效期，最后会导致登不进微软，api调用失败。

解决办法：
1，你要是会代码的话，可以分工，把更新token的代码提出来，新建一个workflow专门用来更新token。旧workflow专门用来运行api调用。你要是要的话，我可以帮你写一个酱紫。
2，启动次数增多，每次轮数减少。每10分钟3轮这样子。应该就不会出错了吧？

我觉得把，并不用这么频繁，一天一次都嫌多。开发应用不一定每时每刻都在调用api，大部分时间是在写代码。所以吧，我觉得“开发活跃”是只要偶尔调用一下就行了。毕竟以前的人都是搭个oneindex就续成了，在最后一个月调用一下outlook也续成了。

刚刚用小号登了ORZ

**Comment by lengyihan7** [comment]
ok。没必要这么麻烦，改下crontab吧。

**Comment by lengyihan7** [comment]
对了，你这个定时语法写的有点问题，不能直接用crontab格式，要用个“”包起来，不然你 * 在第一个的话识别不了，你数字第一个还能识别（0 */6 * * *），我这个（*/10 * * * *）识别不出来，一直以为哪里有问题。后来看到一个例子才反应过来，（"*/10 * * * *"）就行了。你没事时改一下吧，方便后面的人自己改。

**Comment by wangziyingwen** [comment]
好的，感谢
