### ISSUE TITLE
这个是什么错误啊

### ISSUE THREAD

**Issue by zryyyy** [wangziyingwen/AutoApiSecret#27]
Test Api 1s
##[error]Process completed with exit code 1.
Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  File "2.py", line 11
    ***
     ^
SyntaxError: invalid syntax
##[error]Process completed with exit code 1.

**Comment by zryyyy** [comment]
刚刚少了两行
Test Api 1s
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  python 2.py
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
  File "2.py", line 11
    ***
     ^
SyntaxError: invalid syntax
##[error]Process completed with exit code 1.

**Comment by xenud** [comment]
Send your 2.py code

**Comment by zryyyy** [comment]
貌似没这个文件啊......................不过我现在好了，貌似是secrets的问题
