### ISSUE TITLE
##[error]Process completed with exit code 1.

### ISSUE THREAD

**Issue by chengrutw** [wangziyingwen/AutoApiSecret#3]
Hi,

I followed your tutorials to run the scripts and it went smooth until a few days ago. 
This is the error message I got:
##[error]Process completed with exit code 1.

Could you please advise this exit code?
Thanks!

**Comment by wangziyingwen** [comment]
I need a screenshot to confirm the complete error code. 
我需要截图确认哪里出问题了。

**Comment by chengrutw** [comment]
![A4376A0F-36D7-43C3-9177-DB45876FC2F6](https://user-images.githubusercontent.com/35156500/78501841-4253b700-7790-11ea-9518-7e9404b249e7.png)

**Comment by wangziyingwen** [comment]
It shows the refresh_token is wrong.  Please confirm that the refresh_token format is correct. Please follow the tutorial carefully, you better clear the browser cache data,then get the refresh_token again and make sure.

它显示refresh_token错了，这种情况一般是token格式错误了，请严格按照教程描述实行，确保复制对refresh_token而不是access_token，确保1.txt开头跟结束没有空格/空行（github网页的新建文件貌似会自动加空行）。最好重新获取token再尝试。
