### ISSUE TITLE
Test Api中出现了一些奇怪的返回 

### ISSUE THREAD

**Issue by KJZH001** [wangziyingwen/AutoApiSecret#31]
## 问题描述
最开始是正常的，按照教程部署完以后一切都是正常情况
不过后来突然出现了
```
Traceback (most recent call last):
  File "2.py", line 86, in <module>
    main()
  File "2.py", line 42, in main
    access_token=gettoken(refresh_token)
  File "2.py", line 31, in gettoken
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
##[error]Process completed with exit code 1.
```
因为返回的KeyError中提示为refresh_token
所以我去Azure AD中重新开了一个机密并且使用rclone工具重新取得了refresh_token
触发Actions后查看脚本正常运行，不过返回的内容变成了这样
```
1调用成功1次
2调用成功2次
3调用成功3次
8调用成功4次
1调用成功5次
2调用成功6次
3调用成功7次
8调用成功8次
1调用成功9次
2调用成功10次
3调用成功11次
8调用成功12次
```
顺带一提，我发现我自己之前部署的两个类似OneIndex的程序差不多同时也罢工了
不知道这个是不是我自己触发了什么东西造成的呢？
如果可以的话，请麻烦帮忙解答一下~
感激不尽！

**Comment by KJZH001** [comment]
补充一下
因为之前注册的程序得到的结果是可以正常运行的
我这次也只是重新开了一遍机密...所以应该可以排除权限配置方面的问题...
如果可以的话请麻烦解答一下~谢谢~
Fork的仓库地址
https://github.com/KJZH001/AutoApiSecret/

**Comment by KJZH001** [comment]
> > 补充一下
> > 因为之前注册的程序得到的结果是可以正常运行的
> > 我这次也只是重新开了一遍机密...所以应该可以排除权限配置方面的问题...
> > 如果可以的话请麻烦解答一下~
> > 谢谢~
> > Fork的仓库地址
> > https://github.com/KJZH001/AutoApiSecret/
> 
> 我也是只有1、2、3、8被调用。不知道你的问题解决了不？

还没有呢= =

**Comment by xfy99** [comment]
同样的问题，有什么进展了吗？

**Comment by xfy99** [comment]
> 同样的问题，有什么进展了吗？

https://github.com/wangziyingwen/AutoApiSecret/issues/16#issuecomment-630744279

**Comment by wangziyingwen** [comment]
一个个不看readme，就在这儿问！
基本目前所有问题跟解决方案我都写进去了！
确保排除掉所说的几种情况，如果还无法集齐api，只能是账号问题，只能找客服

**Comment by superstoney** [comment]
经测试，应该使用你的***@***.onmicrosoft.com帐号（e5管理员账号登录网站）申请的api及对应的key，不能用错了

**Comment by KJZH001** [comment]
> 一个个不看readme，就在这儿问！
> 基本目前所有问题跟解决方案我都写进去了！
> 确保排除掉所说的几种情况，如果还无法集齐api，只能是账号问题，只能找客服

非常抱歉，过来这么多天才来回复
如果我的问题让您感到生气的话请容许我在此向您道歉
至少我可以向您保证我是看了readme中的常见问题和解决方案后无法解决才来发issue的

后来我最终在Azure AD中重新申请了一个应用并且重新重复了一遍教程，虽然不知道为什么，但是问题确实解决了

虽然您并没有直接给出较为有用的建议，不过我最后在这里还是在这里感谢您的回复

**Comment by KJZH001** [comment]
结合我的经历，因为我之前所申请的所有应用程序似乎都出现了问题
所有我怀疑可能是因为我之前修改了我的申请应用的Microsoft全局账户的邮箱地址导致的
虽然也可能不是这个原因导致的，不过我也希望您可以将它列入常见问题中供大家进行参考
最后，感谢您的回复和对这个项目的制作以及付出
