### ISSUE TITLE
waterelegance是谁呀

### ISSUE THREAD

**Issue by eric15342335-tech** [wangziyingwen/AutoApiSecret#47]
就问问(・∀・)

**Comment by 571241436** [comment]
？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: eric15342335-tech <notifications@github.com&gt;
发送时间: 2020年12月19日 20:02
收件人: wangziyingwen/AutoApiSecret <AutoApiSecret@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[wangziyingwen/AutoApiSecret] waterelegance是谁呀 (#47)





 
就问问(・∀・)

**Comment by eric15342335-tech** [comment]
![waterelegance](https://user-images.githubusercontent.com/76025970/102954915-a3364180-450f-11eb-945a-b1eb65ace4ae.png)
这个账号出现在我的repo 的commit里

或者说这是什么email账号
![email_2](https://user-images.githubusercontent.com/76025970/102955379-ba296380-4510-11eb-9eaa-95a993f44b66.png)

**Comment by wangziyingwen** [comment]
无关紧要，更新文件需要提供一些信息（id，邮箱），这个可以在yml文件里改
