### ISSUE TITLE
我看我现在成功了  但是e5的面板上的时间还是在减少么

### ISSUE THREAD

**Issue by nick814** [wangziyingwen/AutoApiSecret#48]
刚申请好的时候是90天，现在每天都在减少一天 这是没成功？
action里都是成功的

**Comment by 571241436** [comment]
... 剩十几天的时候就成功续约了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nick814 <notifications@github.com&gt;
发送时间: 2020年12月21日 11:45
收件人: wangziyingwen/AutoApiSecret <AutoApiSecret@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[wangziyingwen/AutoApiSecret] 我看我现在成功了  但是e5的面板上的时间还是在减少么 (#48)





 
刚申请好的时候是90天，现在每天都在减少一天 这是没成功？
 action里都是成功的

**Comment by nick814** [comment]
> ...• iphone
> [...](#)
> ------------------ 原始邮件 ------------------ 发件人: nick814 <notifications@github.com&gt; 发送时间: 2020年12月21日 11:45 收件人: wangziyingwen/AutoApiSecret <AutoApiSecret@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[wangziyingwen/AutoApiSecret] 我看我现在成功了 但是e5的面板上的时间还是在减少么 (#48) 刚申请好的时候是90天，现在每天都在减少一天 这是没成功？ action里都是成功的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

要等这么久

**Comment by eric15342335-tech** [comment]
> 
> 
> 刚申请好的时候是90天，现在每天都在减少一天 这是没成功？
> action里都是成功的

e5应该是等到快没了的时候才帮你续约的
