### ISSUE TITLE
PushChanges报错

### ISSUE THREAD

**Issue by Sun020422** [wangziyingwen/AutoApiSecret#50]
Run ad-m/github-push-action@master
  with:
    github_token: ***
    branch: main
    directory: .
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
Push to branch main
To https://github.com/Sun020422/AutoApiSecret.git
 ! [rejected]        HEAD -> main (fetch first)
error: failed to push some refs to 'https://github.com/Sun020422/AutoApiSecret.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

麻烦大神

**Comment by hqiii** [comment]
我找到了解决方案，先打开分支页面，删除main分支，然后在`/.github/workflows/autoWakeup.yml`最底部`github_token: ${{ secrets.GITHUB_TOKEN }}`后回车加一行`branch: master`即可。
类似的引用ad-m/github-push-action库的所有Github Action都可以通过此方式修复。

**Comment by hqiii** [comment]
今天下午我突然接到了Github发来的邮件警告，然后研究了半天。
Github好像近期将默认branch修改为了main，于是push-action就随之更新了，详见 [Default branch should be "main" not "master" #68](https://github.com/ad-m/github-push-action/issues/68)
或者也可以换成`branch: ${{ github.ref }}`可能也可以解决问题（未尝试）。

**Comment by Sun020422** [comment]
> 我找到了解决方案，先打开分支页面，删除main分支，然后在`/.github/workflows/autoWakeup.yml`最底部`github_token: ${{ secrets.GITHUB_TOKEN }}`后回车加一行`branch: master`即可。
> 类似的引用ad-m/github-push-action库的所有Github Action都可以通过此方式修复。

已解决，感谢！
