### ISSUE TITLE
Post change出错

### ISSUE THREAD

**Issue by Micraow** [wangziyingwen/AutoApiSecret#51]
https://github.com/Micraow/AutoApiSecret/actions

本来好好的，前不久突然有这个问题，麻烦帮我看看，我什么设置也没改。

**Comment by Micraow** [comment]
Time.log删不掉，1.txt也不更新了

**Comment by hqiii** [comment]
我找到了解决方案，先打开分支页面，删除main分支，然后在`/.github/workflows/autoWakeup.yml`最底部`github_token: ${{ secrets.GITHUB_TOKEN }}`后回车加一行`branch: master`即可。
类似的引用ad-m/github-push-action库的所有Github Action都可以通过此方式修复。

**Comment by hqiii** [comment]
今天下午我突然接到了Github发来的邮件警告，然后研究了半天。
Github好像近期将默认branch修改为了main，于是push-action就随之更新了，详见 [Default branch should be "main" not "master" #68](https://github.com/ad-m/github-push-action/issues/68)
或者也可以换成`branch: ${{ github.ref }}`可能也可以解决问题（未尝试）。

**Comment by yuanhe-xia** [comment]
> 我找到了解决方案，先打开分支页面，删除main分支，然后在`/.github/workflows/autoWakeup.yml`最底部`github_token: ${{ secrets.GITHUB_TOKEN }}`后回车加一行`branch: master`即可。
> 类似的引用ad-m/github-push-action库的所有Github Action都可以通过此方式修复。

感谢，问题已解决

**Comment by q56535** [comment]
@hqiii 我已经添加了`branch: master`，但Post change仍然出错，如图所示
![已添加branch: master](https://i.loli.net/2021/01/02/VdJn9WMcGt73OU6.png)
Post change错误信息
![Post change错误信息](https://i.loli.net/2021/01/02/tBSJnPTezvoYbUx.png)

**Comment by hqiii** [comment]
@q56535 根据你的运行日志，我看了你的项目文件。
您更新了autoapi.yml后，没有重新进行Star，所以您看到的错误日志应该还是旧的代码运行得到的，您可点击右上角的Star标志，手动开启运行WorkFlow。
如果进行上述操作后仍出现错误，那么我认为您创建的Personal Access Token应该是没有赋予`workflow`权限。
如下图。
![image](https://user-images.githubusercontent.com/61732448/103459152-f1391980-4d47-11eb-9228-c7bef38308aa.png)

**Comment by q56535** [comment]
> @q56535 根据你的运行日志，我看了你的项目文件。
> 您更新了autoapi.yml后，没有重新进行Star，所以您看到的错误日志应该还是旧的代码运行得到的，您可点击右上角的Star标志，手动开启运行WorkFlow。
> 如果进行上述操作后仍出现错误，那么我认为您创建的Personal Access Token应该是没有赋予`workflow`权限。
> 如下图。
> ![image](https://user-images.githubusercontent.com/61732448/103459152-f1391980-4d47-11eb-9228-c7bef38308aa.png)

感谢您的解答，我确实没有star，我重新star后正常了

**Comment by iSteveyang** [comment]
> 今天下午我突然接到了Github发来的邮件警告，然后研究了半天。
> Github好像近期将默认branch修改为了main，于是push-action就随之更新了，详见 [Default branch should be "main" not "master" #68](https://github.com/ad-m/github-push-action/issues/68)
> 或者也可以换成`branch: ${{ github.head_ref }}`可能也可以解决问题（未尝试）。

您好，我尝试了：`branch: ${{ github.head_ref }}`
报错：
```
Push to branch 
fatal: invalid refspec 'HEAD:'
```
还是直接master正常

**Comment by cdncomco** [comment]
https://github.com/wangziyingwen/Autoapi-test 这里把主分支改成main再把master删掉就好了呀

**Comment by hqiii** [comment]
> https://github.com/wangziyingwen/Autoapi-test 这里把主分支改成main再把master删掉就好了呀

嗯，这个方法简单
感谢

**Comment by HandsomeLiu233** [comment]
感谢，修改分支为main之后已经成功

**Comment by HiderX** [comment]
怎么改呢 setting里搞完还是报错

**Comment by HiderX** [comment]
> https://github.com/wangziyingwen/Autoapi-test 这里把主分支改成main再把master删掉就好了呀

怎么删掉？

**Comment by cdncomco** [comment]
![image](https://user-images.githubusercontent.com/51789371/103460143-fc437800-4d4e-11eb-80e2-d48212c9facc.png)

**Comment by HiderX** [comment]
![Uploading Screenshot_20210102_231304_com.huawei.browser.jpg…]()

**Comment by Abson2** [comment]
今晚突然失效，我重新更新了参数，能调用api了，但是又出现了新错误
![image](https://user-images.githubusercontent.com/68466724/103461194-7ed03580-4d57-11eb-861e-799581bf86e9.png)

**Comment by LexsionAuto** [comment]
> ~我找到了解决方案，先打开分支页面，删除main分支，然后在`/.github/workflows/autoWakeup.yml`最底部`github_token: ${{ secrets.GITHUB_TOKEN }}`后回车加一行`branch: master`即可。 类似的引用ad-m/github-push-action库的所有Github Action都可以通过此方式修复。~
> 
> 感谢各位的指点，@cdncomco 的方法最佳，
> **报错后，直接在分支界面修改Default Branch为main即可。**

改完需要重新Star一下，否则还是不行

**Comment by louiejordan** [comment]
按照上面的方法，昨天可以，今天又不行了

**Comment by Tiannary** [comment]
> 按照上面的方法，昨天可以，今天又不行了

一样的情况，我报错是这个
```
Error: Invalid status code: 404
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:14:21)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by xiaoyin01** [comment]
同样的情况 昨天按照上面的方法不报错了 今天又报错了

**Comment by wtyqqq** [comment]
又炸了加一
`Error: Invalid status code: 404
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:14:21)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

**Comment by huoshenlaile** [comment]
我上午还可以的, 下午刚刚几分钟前不行了. 以及请问一下怎么删除master分支

**Comment by nick814** [comment]
我也这样 就刚才又不行了

**Comment by nick814** [comment]
我刚才改了下  最后加了branch: main  然后在把master分支删了，现在运行了下 ok了  
2个方法都用了  明天在看看有没有报错

**Comment by iSteveyang** [comment]
设定了default branch 删除不删除问题应该不大，
1. 如果你的default branch是main：在/.github/workflows/autoWakeup.yml最底部github_token: ${{ secrets.GITHUB_TOKEN }}后加一行branch: main，注意缩进。
2. 如果default branch是master：

> 然后在/.github/workflows/autoWakeup.yml最底部github_token: ${{ secrets.GITHUB_TOKEN }}后回车加一行branch: master即可。
应该没啥问题了

**Comment by minitru1014** [comment]
昨天设置完了可以了 今天又gg了

**Comment by nick814** [comment]
> 昨天设置完了可以了 今天又gg了

兄弟 你按照我的方法来下  后面加下        branch: main   
然后在把master分支删掉试试看

**Comment by louiejordan** [comment]
> 设定了default branch 删除不删除问题应该不大，
> 
> 1. 如果你的default branch是main：在/.github/workflows/autoWakeup.yml最底部github_token: ${{ secrets.GITHUB_TOKEN }}后加一行branch: main，注意缩进。
> 2. 如果default branch是master：
> 
> > 然后在/.github/workflows/autoWakeup.yml最底部github_token: ${{ secrets.GITHUB_TOKEN }}后回车加一行branch: master即可。
> 
> 应该没啥问题了

这个是对的，昨天写的master，所以报错了

**Comment by wuhaozede** [comment]
> 设置了默认分支删除不删除问题应该不大，
> 
> 1. 如果您的默认分支是main：在/.github/workflows/autoWakeup.yml最底部github_token：$ {{secrets.GITHUB_TOKEN}}后加一行分支：main，注意缩进。
> 2. 如果默认分支是主人：
> 
> > 然后在/.github/workflows/autoWakeup.yml最底部github_token：$ {{secrets.GITHUB_TOKEN}}后回车加一行branch：master即可。
> 
> 应该没啥问题了

这样是可以的

**Comment by minitru1014** [comment]
> > 昨天设置完了可以了 今天又gg了
> 
> 兄弟 你按照我的方法来下 后面加下 branch: main
> 然后在把master分支删掉试试看

老哥 顺便问一下 如何删除master分支

**Comment by minitru1014** [comment]
> > 昨天设置完了可以了 今天又gg了
> 
> 兄弟 你按照我的方法来下 后面加下 branch: main
> 然后在把master分支删掉试试看

找到了 谢谢拉
