### ISSUE TITLE
workflow出现了一些问题

### ISSUE THREAD

**Issue by liukenny961** [wangziyingwen/AutoApiSecret#53]
您好！
最近当我执行workflow时，出现了一些问题：
![屏幕截图 2021-01-02 212124](https://user-images.githubusercontent.com/65520199/103458373-365a4d00-4d42-11eb-92e5-09a3f37e9f48.png)
请问是什么原因呢？如何解决呢？

**Comment by pishen12138** [comment]
可以看上一个issues，提出了解决这个问题的方法

**Comment by liukenny961** [comment]
好的，谢谢。

**Comment by liukenny961** [comment]
您好！
通过上一个issue，该问题已经解决。感谢您的技术支持。
