### ISSUE TITLE
GitHub Time.log无法提交

### ISSUE THREAD

**Issue by i-am-a-loser-using-windows-server** [wangziyingwen/AutoApiSecret#64]
![image](https://user-images.githubusercontent.com/64469437/103539613-5a00cd00-4ed3-11eb-9323-879293ca8c17.png)
如图，初步推测API调用应该是成功的，但是log更新失败了而已
![image](https://user-images.githubusercontent.com/64469437/103539825-b19f3880-4ed3-11eb-9693-088b3d47a909.png)

**Comment by wangziyingwen** [comment]
自己看常见错误
