### ISSUE TITLE
今天重新Fork了一遍就炸了

### ISSUE THREAD

**Issue by HanHan233** [wangziyingwen/AutoApiSecret#68]
![image](https://user-images.githubusercontent.com/64469437/104575914-887c6600-5692-11eb-8d27-849179d68053.png)
几个Workflow错误均是这样
![image](https://user-images.githubusercontent.com/64469437/104576150-c9747a80-5692-11eb-8efa-c0be492f4a47.png)

由于最近一直Push错误所以今天重新Fork了一遍，按教程操作一切无误，但是workflow无法运行(换AutoAPIP后正常)，经检查refresh_token没有额外空格与回车等错误，各种secret也是最新正常的。

**Comment by register110** [comment]
语法问题，注意缩进和中英切换

**Comment by HanHan233** [comment]
我确信标点的全/半角，中英问以及缩进无任何问题（反正都不用啦）

> 语法问题，注意缩进和中英切换
