### ISSUE TITLE
Github Actions 限制的问题

### ISSUE THREAD

**Issue by yang05051** [wangziyingwen/AutoApiSecret#8]
我设置成每小时运行100次，会不会触发 Github Actions 的限制？

**Comment by wangziyingwen** [comment]
多少次没关系，最短每5分钟启动一个action。还有secret版不能重叠运行，会报错，不过这个报错没影响，但是得保证每天有一个是成功运行的。

**Comment by yang05051** [comment]
好的，谢谢 😀
